version: "3.5"
services:
  web:
    build: server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  angular:
    build: client # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port mapping
    volumes:
      - ./client:/usr/src/app
